### ISSUE TITLE
Java run crashes when there is no subject, or subject starts with a space

### ISSUE THREAD

**Issue by boris-noyvert** [TeWu/GmailAttachmentsExtractor#2]
When GmailAttachmentsExtractor encounters an email with no subject or a subject starting with a space, it produces the following output and stops:

```
8/87 (9%) | Processing email ''
java.nio.file.InvalidPathException: Trailing char < > at index 19: 2020.03.08 17_04_46
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at sun.nio.fs.AbstractPath.resolve(Unknown Source)
        at pl.geek.tewu.gmail_attachments_extractor.GmailAttachmentsExtractor.createDirForAttachments(GmailAttachmentsExtractor.java:241)
        at pl.geek.tewu.gmail_attachments_extractor.GmailAttachmentsExtractor.extractAttachments(GmailAttachmentsExtractor.java:140)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:45)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:14)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at pl.geek.tewu.gmail_attachments_extractor.Main.main(Main.java:29)
```

The command that was used is the following:

```
java -jar GmailAttachmentsExtractor.jar --min-size 100k -l larger20MB_again2  larger:20M larger20MB_again2
```

Since I have quite a few emails with photos that don't have a subject, this bug unfortunately prevents me from using GmailAttachmentsExtractor for automatic extraction of attachments, since it stops every time on an email with empty subject field and I have to deal with it manually. Otherwise it is a great idea and I hope it is not too difficult to fix this issue.

Thank you!

**Comment by TeWu** [comment]
Thank you for reporting this.
It should work now. Be sure you're using the new version [1.0.1](https://github.com/TeWu/GmailAttachmentsExtractor/releases/tag/1.0.1).

**Comment by boris-noyvert** [comment]
Thank you!
Yes, it works most of the time now.
Is there a limit of 100 emails? It seems that it only finds the first 100 emails satisfying the filter and then processes them.
Also seems to ignore certain attachments - some pdf and mp4 files, but not sure which exactly (the comment is "Email doesn't contain attachments that satisfy the filter - proceeding to the next email").
I will create an issue about 100 emails, not sure about missed attachments.
Thanks a lot!
