### ISSUE TITLE
Missing 'Subject' header causes NullPointerException

### ISSUE THREAD

**Issue by shyderc** [TeWu/GmailAttachmentsExtractor#7]
I used Gmail API to find this message and it has no subject.  
```
268/~657 (40%) | Processing email 14df9d22d4610a74
java.lang.NullPointerException: Cannot invoke "String.length()" because "name" is null
        at pl.geek.tewu.gmail_attachments_extractor.Utils.sanitizeFSName(Utils.java:76)
        at pl.geek.tewu.gmail_attachments_extractor.Utils.sanitizeDirName(Utils.java:72)
        at pl.geek.tewu.gmail_attachments_extractor.GmailAttachmentsExtractor.createDirForAttachments(GmailAttachmentsExtractor.java:255)
        at pl.geek.tewu.gmail_attachments_extractor.GmailAttachmentsExtractor.extractAttachments(GmailAttachmentsExtractor.java:142)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:45)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:14)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at pl.geek.tewu.gmail_attachments_extractor.Main.main(Main.java:29)
```

**Comment by TeWu** [comment]
Thanks for reporting.

**Comment by shyderc** [comment]
I compiled your latest commits and am running now.  Thank you.
