### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by shyderc** [TeWu/GmailAttachmentsExtractor#9]
Can there be a retry on this error?
```
proceeding to the next email
java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:981)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1434)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1623)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:105)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at pl.geek.tewu.gmail_attachments_extractor.GmailAttachmentsExtractor.extractAttachments(GmailAttachmentsExtractor.java:111)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:45)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:14)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at pl.geek.tewu.gmail_attachments_extractor.Main.main(Main.java:29)
```

**Comment by shyderc** [comment]
I have saved over 15GB of attachments because of your work.  Thank you!
I have over 180k messages to go through.
A new build would be great.

**Comment by shyderc** [comment]
This is the only issue I have now.  
Best progress so far 47083/~53642
But got 'Read timed out'

**Comment by shyderc** [comment]
New error that I am not sure if it is a different issue?
```
54166/~60642 (89%) | Processing email 'Invoice #2020622'
    Email doesn't contain attachments that satisfy the filter - proceeding to the next email
java.net.UnknownHostException: www.googleapis.com
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
        at java.base/java.net.Socket.connect(Socket.java:648)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:104)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at pl.geek.tewu.gmail_attachments_extractor.GmailAttachmentsExtractor.extractAttachments(GmailAttachmentsExtractor.java:113)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:45)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:14)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at pl.geek.tewu.gmail_attachments_extractor.Main.main(Main.java:29)
```

**Comment by TeWu** [comment]
Thanks for reporting. 
It makes sense to retry on network errors. I'm gonna work on this.

**Comment by shyderc** [comment]
Should I create issues for each error I see?  Furthest I got so far!

```
84692/~88587 (95%) | Processing email 'RE: End of 7th day'
    Extracting 1 attachment(s) to directory '2016.08.30 00_08_14 RE_ End of 7th day'
    Attachment NOT saved: image.png
java.lang.RuntimeException: One of attachments hasn't been exported properly
        at pl.geek.tewu.gmail_attachments_extractor.GmailAttachmentsExtractor.extractAttachments(GmailAttachmentsExtractor.java:195)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:45)
        at pl.geek.tewu.gmail_attachments_extractor.Main.call(Main.java:14)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at pl.geek.tewu.gmail_attachments_extractor.Main.main(Main.java:29)
PS C:\Users\shyde\Downloads\GmailAttachmentsExtractor>
```

**Comment by TeWu** [comment]
You have a lot of emails to process 😃. Here are few pieces of advice that I have for you:

1. Add `has:attachment` to your query string, to process only emails with attachments.
2. If after adding `has:attachment` you still have more then 10000 emails to process, break it up into batches, and run GmailAttachmentExtractor one time for each batch. This way, when the run fails, you will have to only retry running extractor for the current batch. You can use `before`, and `after` in your query string to limit the number of emails that are returned by the query, e.g: `after:2016/04/19` . See [this page](https://support.google.com/mail/answer/7190?hl=en) to learn more about gmail search operators.
3. You may be experiencing network errors because you're exceeding the Gmail API quota. To help with that, I've added `--inter-message-wait` option. Setting it to `200`, should be enough but you can try `300`, `500` or more. That might be obvious, but if you getting a lot of network errors, you may try to make sure you have a good internet connection before running the program (e.g. not wireless).
4. You've also reported some errors that are the results of failed safety checks e.g. `java.lang.RuntimeException: One of attachments hasn't been exported properly`. Those checks might sometimes produce false negatives (or false alarms). If you encounter those errors, you can use `--no-validate` option to bypass those checks. To maximally benefit from those safety checks, you should avoid using `--no-validate`, and only use this option to run the extractor for a single, problematic email. You can run the program for a single email by targetting this email by its Message-ID, To do that use query string  `rfc822msgid:<MESSAGE-ID>`, replacing `<MESSAGE-ID>` with email's Message-ID. [Here](https://www.youtube.com/watch?v=rgZzzepMZmw&t=19s) you have instructions how to find email's Message-ID. Also when using `--no-validate` option, be sure to manually verify that the attachments has been exported correctly.

I hope this helps 😄 

---

When it comes to implementing 'retry on network errors' behaviour, I decided that I'm not gonna do this for now.
I don't want to implement retrying on network errors because some requests issued by the program are not idempotent. Properly handling this idempotence would require me to make the program more complex, which I want to avoid. I want to keep the program small, simple and robust. Also the program already have some small amount of resilience to network errors, which I believe is enough. Also I do believe you can solve most network issues by combination of using `--inter-message-wait 300`, and just making sure, you run the extractor from a place with a good, stable internet connection.

**Comment by shyderc** [comment]
After processing 100k's of emails I have only had 'read timeout' error a few times.
My internet is excellent.  My last run went over 97k emails without failure.
My downloaded attachments folder is 13.5GB and has almost 25k objects in it.
This tool is the only one that has done so well.    Thank you!
I will adjust the query to use 'has:attachment'.  Perhaps consider adding it by default?
